In [18]:
import numpy as np

# Seed for reproducibility
np.random.seed(0)

# Generate X as a 5x2 matrix with values -1 and 1
X = np.random.choice([-1, 1], size=(5, 2))

# Define the linear generating process
coefficients = np.array([2, -3])
intercept = 1

# Generate Y using the linear model
Y = X @ coefficients

# Print the binary dataset with -1 and 1
print("X (original, -1 and 1):\n", X)
print("Y (real-valued):\n", Y)

# Convert X to 0 and 1
X_zero_one = (X + 1) // 2

# Print the binary dataset with 0 and 1
print("X (0 and 1):\n", X_zero_one)
print("Y (real-valued):\n", Y)


X (original, -1 and 1):
 [[-1  1]
 [ 1 -1]
 [ 1  1]
 [ 1  1]
 [ 1  1]]
Y (real-valued):
 [-5  5 -1 -1 -1]
X (0 and 1):
 [[0 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]]
Y (real-valued):
 [-5  5 -1 -1 -1]


In [19]:
(np.linalg.inv(X.T@X)@X.T@Y) * 2 -1

array([ 3., -7.])

In [20]:
np.linalg.inv(X_zero_one.T@X_zero_one)@X_zero_one.T@Y

array([ 4.57142857, -5.42857143])